Add necessary docker files
Seeing
```
 > [cacher 9/9] RUN cargo chef cook --offline --recipe-path recipe.json:
#20 1.101 error: the listed checksum of `/opt/hellow/vendor/rocket/tests/file_server.rs` has changed:
#20 1.101 expected: 160173f59a4bf801bf893d952927d5d03a2baa4f7e5b94e193bf28e2b109fa4f
#20 1.101 actual:   e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
#20 1.101
#20 1.101 directory sources are not intended to be edited, if modifications are required then it is recommended that `[patch]` is used with a forked copy of the source
#20 1.103 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.21/src/recipe.rs:136:27
#20 1.103 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
executor failed running [/bin/sh -c cargo chef cook --offline --recipe-path recipe.json]: exit code: 101
```
Separately, should maybe read `.cargo/config.toml` and
ignore the files in those directories